---
- name: Setup prerequisites
  hosts: workers, controllers
  vars:
    auxiliary_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
  roles:
    - role: hostname_kernel_setup
    - role: cri_setup
    - role: kube_components_setup

- name: Setup Kubernetes Control Plane
  tags: controllers
  hosts: controllers
  roles:
    - role: single_control_plane_setup

- name: Setup Kubernetes Worker Nodes
  tags: workers
  hosts: workers
  roles:
    - role: worker_node_setup

- name: Setup Local Admin for cluster access
  tags: localhost
  hosts: localhost
  become: false
  tasks:
    - name: Generating an OpenSSL Private Key
      community.crypto.openssl_privatekey:
        path: /tmp/local-admin.key
        size: 2048
        mode: 0644

    - name: Generating an OpenSSL CSR
      community.crypto.openssl_csr:
        path: /tmp/local-admin.csr
        privatekey_path: /tmp/local-admin.key
        common_name: local-admin

    - name: Creating local .kube folder
      file:
        state: directory
        path: ~/.kube

- name: Configure Local Admin inside the cluster
  tags: cluster-localadmin
  hosts: controller
  roles:
    - role: setup_local_admin

- name: Copy the kubeconfig from k8s control node to localhost
  tags: localhost-copy
  hosts: controller
  become: false
  tasks:
    - name: Copy kubeconfig to localhost
      fetch:
        src: /tmp/config
        dest: ~/.kube
        flat: true
        validate_checksum: false

- name: Local cleanup
  hosts: localhost
  tags: local-cleanup
  tasks:
    - name: Removing temp files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/local-admin.csr
        - /tmp/local-admin.key
        - /tmp/join_command.sh
      